#!/bin/bash 
echo "Start Deploy makan do" && sleep 60 
echo"1 Circleci.....GOSI" 	&& sleep 60
echo"2 Circleci.....GOSI" 	&& sleep 60
echo"3 Circleci.....GOSI" 	&& sleep 60
echo"4 Circleci.....GOSI" 	&& sleep 60
echo"5 Circleci.....GOSI" 	&& sleep 60
echo"6 Circleci.....GOSI" 	&& sleep 60
echo"7 Circleci.....GOSI" 	&& sleep 60
echo"8 Circleci.....GOSI" 	&& sleep 60
echo"9 Circleci.....GOSI" 	&& sleep 60
echo"10 Circleci.....GOSI" 	&& sleep 60
echo"11 Circleci.....GOSI" 	&& sleep 60
echo"12 Circleci.....GOSI" 	&& sleep 60
echo"13 Circleci.....GOSI" 	&& sleep 60
echo"14 Circleci.....GOSI" 	&& sleep 60
echo"15 Circleci.....GOSI" 	&& sleep 60
echo"16 Circleci.....GOSI" 	&& sleep 60
echo"17 Circleci.....GOSI" 	&& sleep 60
echo"18 Circleci.....GOSI" 	&& sleep 60
echo"19 Circleci.....GOSI" 	&& sleep 60
echo"20 Circleci.....GOSI" 	&& sleep 60
echo"21 Circleci.....GOSI" 	&& sleep 60
echo"22 Circleci.....GOSI" 	&& sleep 60
echo"23 Circleci.....GOSI" 	&& sleep 60
echo"24 Circleci.....GOSI" 	&& sleep 60
echo"25 Circleci.....GOSI" 	&& sleep 60
echo"26 Circleci.....GOSI" 	&& sleep 60
echo"27 Circleci.....GOSI" 	&& sleep 60
echo"28 Circleci.....GOSI" 	&& sleep 60
echo"29 Circleci.....GOSI" 	&& sleep 60
echo"30 Circleci.....GOSI" 	&& sleep 60
echo"31 Circleci.....GOSI" 	&& sleep 60
echo"32 Circleci.....GOSI" 	&& sleep 60
echo"33 Circleci.....GOSI" 	&& sleep 60
echo"34 Circleci.....GOSI" 	&& sleep 60
echo"35 Circleci.....GOSI" 	&& sleep 60
echo"36 Circleci.....GOSI" 	&& sleep 60
echo"37 Circleci.....GOSI" 	&& sleep 60
echo"38 Circleci.....GOSI" 	&& sleep 60
echo"39 Circleci.....GOSI" 	&& sleep 60
echo"40 Circleci.....GOSI" 	&& sleep 60
echo"41 Circleci.....GOSI" 	&& sleep 60
echo"42 Circleci.....GOSI" 	&& sleep 60
echo"43 Circleci.....GOSI" 	&& sleep 60
echo"44 Circleci.....GOSI" 	&& sleep 60
echo"45 Circleci.....GOSI" 	&& sleep 60
echo"46 Circleci.....GOSI" 	&& sleep 60
echo"47 Circleci.....GOSI" 	&& sleep 60
echo"48 Circleci.....GOSI" 	&& sleep 60
echo"49 Circleci.....GOSI" 	&& sleep 60
echo"50 Circleci.....GOSI" 	&& sleep 60
echo"51 Circleci.....GOSI" 	&& sleep 60
echo"52 Circleci.....GOSI" 	&& sleep 60
echo"53 Circleci.....GOSI" 	&& sleep 60
echo"54 Circleci.....GOSI" 	&& sleep 60
echo"55 Circleci.....GOSI" 	&& sleep 60
echo"56 Circleci.....GOSI" 	&& sleep 60
echo"57 Circleci.....GOSI" 	&& sleep 60
echo"58 Circleci.....GOSI" 	&& sleep 60
echo "DEPLOY SUKSESS 😎"
